import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container__main}>
        <section className={styles.container__main__landing}>
          <div className={styles.container__main__landing__headline}>
            <h2 className={styles.container__main__landing__headline__title}>
              All the headlines you need...
            </h2>
          </div>
        </section>
        <section className={styles.container__main__info}>
          <h2 className={styles.container__main__info__title}>
            Sourced from over 60,000 news outlets...
          </h2>
          <Link href="/world">
            <button className={styles.container__main__info__button}>Get Started</button>
          </Link>
        </section>
      </main>
    </div>
  )
}

export default Home
