import type { NextPage } from 'next'
import Head from 'next/head'
import { useArticles } from '../context/ArticlesContext'
import { useEffect } from 'react'
import NewsAPI from '../utils/NewsAPI'
import NewsGrid from '../components/NewsGrid/NewsGrid'

const World: NextPage = () => {
  const { articles, updateArticles } = useArticles();

  useEffect(() => {
    const fetchArticles = async () => {
      const fetchedArticles = await NewsAPI.getWorldNews();
      updateArticles(fetchedArticles.data.articles.articles);
      console.log(articles)
    }
    fetchArticles();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NewsGrid articles={articles}/>
      </main>
    </div>
  )
}

export default World